In [ ]:
import pandas as pd
data = {'apples':[3,2,0,1],'oranges':[0,3,7,2]}
df = pd.DataFrame(data)
df.to_csv('fruits.csv')
df

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [ ]:
#student id, name, branch,section
import pandas as pd
student = {'Name':['Pranathi','Parinitha','Dharani','Cherishma','Aruna'],'Id':[10,20,30,40,50],'Branch':['CSE','ECE','CSIT','AIDS','MCA'],'Section':['A','B','C','D','E']}
df = pd.DataFrame(student,index=[1,2,3,4,5])
df.to_json('students.csv')
df
df.loc[1]

Name       Pranathi
Id               10
Branch          CSE
Section           A
Name: 1, dtype: object

In [ ]:
import pandas as pd
df = pd.read_csv('tips.csv',index_col=0)
df

,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
total_bill,,,,,,,,,,
16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...
29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
import pandas as pd
df = pd.read_csv('Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
import pandas as pd
df = pd.read_csv('titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
import pandas as pd
movies = pd.read_csv('movies.csv.zip')
movies
movies.head(5)
movies.tail(2)
movies.info()
movies.shape #4803 rows, 24 columns
movies.describe
movies.drop_duplicates()
movies.shape
x = pd.concat([movies,movies])
x
x.shape #9606 rows, 24 columns
x=x.drop_duplicates()
x.shape
movies.drop_duplicates(inplace=True)

#count total NaN values
total_nan = movies.isna().sum().sum()
#count total NaN values per column
nans_per_coulmn = movies.isna().sum()
print("Total NaNs: ",total_nan)
print("NaNs per column: ",nans_per_coulmn)

movies.dropna()
movies.fillna(0)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  title                 4803 non-null   object
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   object
 22  crew                  4803 non-null   object
 23  director              4773 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB
Total NaNs:  4454
NaNs per column:  index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,4798,220000,Action Crime Thriller,0,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,0,72766,0,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,0,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,0,http://shanghaicalling.com/,126186,0,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,0,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,0,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [ ]:
#creating a DataFrame with a list of dictionaries, row indices, column indices
import pandas as pd
real = [{'a':1,'b':2},{'a': 5, 'b':10,'c':20}]

df1 = pd.DataFrame(real,index=['first','second'],columns=['a','b'])
df2 = pd.DataFrame(real,index=['first','second'],columns=['a','b1'])

print(df1)
print('...........')
print(df2)

        a   b
first   1   2
second  5  10
...........
        a  b1
first   1 NaN
second  5 NaN

In [ ]:
import pandas as pd
d = {'one':pd.Series([1,2,3],index=['a','b','c']),'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df = pd.DataFrame(d)
#adding a new column to an existing dataframe object
# with column lable by passing new series
df['three']=pd.Series([10,20,30],index=['a','b','c'])
print(df)
print("adding a new column using the existing columns in Dataframe :")
df['four']=df['one']+df['three']
del df['one']
df
print(df)

#slicing
print(df[2:4])

#re_indexing
df1.reindex_like(df2)

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
adding a new column using the existing columns in Dataframe :
   two  three  four
a    1   10.0  11.0
b    2   20.0  22.0
c    3   30.0  33.0
d    4    NaN   NaN
   two  three  four
c    3   30.0  33.0
d    4    NaN   NaN

        a  b1
first   1 NaN
second  5 NaN

In [ ]:
import pandas as pd
import numpy as np
#sample dataset
df = pd.DataFrame({'Age':[25,30,np.nan,40,35], 'Department':['HR','Finance','Finance',np.nan,'IT']})
#Mean for numeric
print(df)
df['Age'].fillna(df['Age'].mean(),inplace=True)
#mode for categorical
df['Department'].fillna(df['Department'].mode()[0],inplace=True)
print(df)

    Age Department
0  25.0         HR
1  30.0    Finance
2   NaN    Finance
3  40.0        NaN
4  35.0         IT
    Age Department
0  25.0         HR
1  30.0    Finance
2  32.5    Finance
3  40.0    Finance
4  35.0         IT

/tmp/ipykernel_1507/4204258815.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)
/tmp/ipykernel_1507/4204258815.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Department'].fillna(df['Department'].mode()[0],inplace=True)

In [ ]:
#forward filling
df_ffill=df.copy()
df_ffill.fillna(method='ffill',inplace=True)
df_ffill

/tmp/ipykernel_1507/996370431.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill.fillna(method='ffill',inplace=True)

    Age Department
0  25.0         HR
1  30.0    Finance
2  32.5    Finance
3  40.0    Finance
4  35.0         IT

In [ ]:
#backward filling
df_bfill = df.copy()
df_bfill.fillna(method='bfill',inplace=True)
df_bfill

/tmp/ipykernel_1507/2201551216.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill.fillna(method='bfill',inplace=True)

    Age Department
0  25.0         HR
1  30.0    Finance
2  32.5    Finance
3  40.0    Finance
4  35.0         IT

In [ ]:
import pandas as pd

# Sample dataset with inconsistent date formats
df = pd.DataFrame({
    'Date': ['2025-01-05', '05/01/2025', 'Jan 5, 2025', '2025.01.05']
})

# Convert all dates to standard ISO format (YYYY-MM-DD)
df['Date'] = pd.to_datetime(df['Date'], errors='coerce').dt.strftime('%Y-%m-%d')

print(df)

         Date
0  2025-01-05
1         NaN
2         NaN
3         NaN

In [ ]:
df = pd.DataFrame({
    'Name': ['Alice', 'BOB', 'charlie', 'DAVID']
})

# Convert all names to lowercase
df['Name_lower'] = df['Name'].str.lower()
print(df)

# Convert all names to uppercase
df['Name_upper'] = df['Name'].str.upper()

print(df)

      Name Name_lower
0    Alice      alice
1      BOB        bob
2  charlie    charlie
3    DAVID      david
      Name Name_lower Name_upper
0    Alice      alice      ALICE
1      BOB        bob        BOB
2  charlie    charlie    CHARLIE
3    DAVID      david      DAVID

In [ ]:
df=pd.read_csv('movies.csv.zip')

# Convert all names to lowercase
df['title_lower'] = df['title'].str.lower()
print(df)

# Convert all names to uppercase
df['title_upper'] = df['title'].str.upper()

print(df)

      index     budget                                    genres  \
0         0  237000000  Action Adventure Fantasy Science Fiction
1         1  300000000                  Adventure Fantasy Action
2         2  245000000                    Action Adventure Crime
3         3  250000000               Action Crime Drama Thriller
4         4  260000000          Action Adventure Science Fiction
...     ...        ...                                       ...
4798   4798     220000                     Action Crime Thriller
4799   4799       9000                            Comedy Romance
4800   4800          0             Comedy Drama Romance TV Movie
4801   4801          0                                       NaN
4802   4802          0                               Documentary

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995
1          http://disney.go.com/disneypictures/pirates/     285
2           http://www.sonypictures.com/movies/spectre/  206647
3                    http://www.thedarkknightrises.com/   49026
4                  http://movies.disney.com/john-carter   49529
...                                                 ...     ...
4798                                                NaN    9367
4799                                                NaN   72766
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617
4801                        http://shanghaicalling.com/  126186
4802                                                NaN   25975

                                               keywords original_language  \
0     culture clash future space war space colony so...                en
1     ocean drug abuse exotic island east india trad...                en
2            spy based on novel secret agent sequel mi6                en
3     dc comics crime fighter terrorist secret ident...                en
4     based on novel mars medallion space travel pri...                en
...                                                 ...               ...
4798  united states\u2013mexico barrier legs arms pa...                es
4799                                                NaN                en
4800  date love at first sight narration investigati...                en
4801                                                NaN                en
4802               obsession camcorder crush dream girl                en

                                original_title  \
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
4798                               El Mariachi
4799                                 Newlyweds
4800                 Signed, Sealed, Delivered
4801                          Shanghai Calling
4802                         My Date with Drew

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...
2     A cryptic message from Bond’s past sends him o...  107.376788  ...
3     Following the death of District Attorney Harve...  112.312950  ...
4     John Carter is a war-weary, former military ca...   43.926995  ...
...                                                 ...         ...  ...
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476  ...
4801  When ambitious New York attorney Sam is sent t...    0.857008  ...
4802  Ever since the second grade when he first saw ...    1.929883  ...

                                       spoken_languages    status  \
0     [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1              [{"iso_639_1": "en", "name": "English"}]  Released
2     [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3              [{"iso_639_1": "en", "name": "English"}]  Released
4              [{"iso_639_1": "en", "name": "English"}]  Released
...                                                 ...       ...
4798      [{"iso_639_1": "es", "name": "Espa\u00f1ol"}]  Released
4799                                                 []  Released
4800           [{"iso_639_1": "en", "name": "English"}]  Released
4801           [{"iso_639_1": "en", "name": "English"}]  Released
4802           [{"iso_639_1": "en", "name": "English"}]  Released

                                                tagline  \
0                           Enter the World of Pandora.
1        At the end of the world, the adventure begins.
2                                 A Plan No One Escapes
3                                       The Legend Ends
4                  Lost in our world, found in another.
...                                                 ...
4798  He didn't come looking for trouble, but troubl...
4799  A newlywed couple's honeymoon is upended by th...
4800                                                NaN
4801                           A New Yorker in Shanghai
4802                                                NaN

                                         title  vote_average vote_count  \
0                                       Avatar           7.2      11800
1     Pirates of the Caribbean: At World's End           6.9       4500
2                                      Spectre           6.3       4466
3                        The Dark Knight Rises           7.6       9106
4                                  John Carter           6.1       2124
...                                        ...           ...        ...
4798                               El Mariachi           6.6        238
4799                                 Newlyweds           5.9          5
4800                 Signed, Sealed, Delivered           7.0          6
4801                          Shanghai Calling           5.7          7
4802                         My Date with Drew           6.3         16

                                                   cast  \
0     Sam Worthington Zoe Saldana Sigourney Weaver S...
1     Johnny Depp Orlando Bloom Keira Knightley Stel...
2     Daniel Craig Christoph Waltz L\u00e9a Seydoux ...
3     Christian Bale Michael Caine Gary Oldman Anne ...
4     Taylor Kitsch Lynn Collins Samantha Morton Wil...
...                                                 ...
4798  Carlos Gallardo Jaime de Hoyos Peter Marquardt...
4799  Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...
4800  Eric Mabius Kristin Booth Crystal Lowe Geoff G...
4801  Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...
4802  Drew Barrymore Brian Herzlinger Corey Feldman ...

                                                   crew           director  \
0     [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron
1     [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski
2     [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes
3     [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan
4     [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton
...                                                 ...                ...
4798  [{'name': 'Robert Rodriguez', 'gender': 0, 'de...   Robert Rodriguez
4799  [{'name': 'Edward Burns', 'gender': 2, 'depart...       Edward Burns
4800  [{'name': 'Carla Hetland', 'gender': 0, 'depar...        Scott Smith
4801  [{'name': 'Daniel Hsia', 'gender': 2, 'departm...        Daniel Hsia
4802  [{'name': 'Clark Peterson', 'gender': 2, 'depa...   Brian Herzlinger

                                   title_lower
0                                       avatar
1     pirates of the caribbean: at world's end
2                                      spectre
3                        the dark knight rises
4                                  john carter
...                                        ...
4798                               el mariachi
4799                                 newlyweds
4800                 signed, sealed, delivered
4801                          shanghai calling
4802                         my date with drew

[4803 rows x 25 columns]
      index     budget                                    genres  \
0         0  237000000  Action Adventure Fantasy Science Fiction
1         1  300000000                  Adventure Fantasy Action
2         2  245000000                    Action Adventure Crime
3         3  250000000               Action Crime Drama Thriller
4         4  260000000          Action Adventure Science Fiction
...     ...        ...                                       ...
4798   4798     220000                     Action Crime Thriller
4799   4799       9000                            Comedy Romance
4800   4800          0             Comedy Drama Romance TV Movie
4801   4801          0                                       NaN
4802   4802          0                               Documentary

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995
1          http://disney.go.com/disneypictures/pirates/     285
2           http://www.sonypictures.com/movies/spectre/  206647
3                    http://www.thedarkknightrises.com/   49026
4                  http://movies.disney.com/john-carter   49529
...                                                 ...     ...
4798                                                NaN    9367
4799                                                NaN   72766
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617
4801                        http://shanghaicalling.com/  126186
4802                                                NaN   25975

                                               keywords original_language  \
0     culture clash future space war space colony so...                en
1     ocean drug abuse exotic island east india trad...                en
2            spy based on novel secret agent sequel mi6                en
3     dc comics crime fighter terrorist secret ident...                en
4     based on novel mars medallion space travel pri...                en
...                                                 ...               ...
4798  united states\u2013mexico barrier legs arms pa...                es
4799                                                NaN                en
4800  date love at first sight narration investigati...                en
4801                                                NaN                en
4802               obsession camcorder crush dream girl                en

                                original_title  \
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
4798                               El Mariachi
4799                                 Newlyweds
4800                 Signed, Sealed, Delivered
4801                          Shanghai Calling
4802                         My Date with Drew

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...
2     A cryptic message from Bond’s past sends him o...  107.376788  ...
3     Following the death of District Attorney Harve...  112.312950  ...
4     John Carter is a war-weary, former military ca...   43.926995  ...
...                                                 ...         ...  ...
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476  ...
4801  When ambitious New York attorney Sam is sent t...    0.857008  ...
4802  Ever since the second grade when he first saw ...    1.929883  ...

        status                                            tagline  \
0     Released                        Enter the World of Pandora.
1     Released     At the end of the world, the adventure begins.
2     Released                              A Plan No One Escapes
3     Released                                    The Legend Ends
4     Released               Lost in our world, found in another.
...        ...                                                ...
4798  Released  He didn't come looking for trouble, but troubl...
4799  Released  A newlywed couple's honeymoon is upended by th...
4800  Released                                                NaN
4801  Released                           A New Yorker in Shanghai
4802  Released                                                NaN

                                         title  vote_average  vote_count  \
0                                       Avatar           7.2       11800
1     Pirates of the Caribbean: At World's End           6.9        4500
2                                      Spectre           6.3        4466
3                        The Dark Knight Rises           7.6        9106
4                                  John Carter           6.1        2124
...                                        ...           ...         ...
4798                               El Mariachi           6.6         238
4799                                 Newlyweds           5.9           5
4800                 Signed, Sealed, Delivered           7.0           6
4801                          Shanghai Calling           5.7           7
4802                         My Date with Drew           6.3          16

                                                   cast  \
0     Sam Worthington Zoe Saldana Sigourney Weaver S...
1     Johnny Depp Orlando Bloom Keira Knightley Stel...
2     Daniel Craig Christoph Waltz L\u00e9a Seydoux ...
3     Christian Bale Michael Caine Gary Oldman Anne ...
4     Taylor Kitsch Lynn Collins Samantha Morton Wil...
...                                                 ...
4798  Carlos Gallardo Jaime de Hoyos Peter Marquardt...
4799  Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...
4800  Eric Mabius Kristin Booth Crystal Lowe Geoff G...
4801  Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...
4802  Drew Barrymore Brian Herzlinger Corey Feldman ...

                                                   crew           director  \
0     [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron
1     [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski
2     [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes
3     [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan
4     [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton
...                                                 ...                ...
4798  [{'name': 'Robert Rodriguez', 'gender': 0, 'de...   Robert Rodriguez
4799  [{'name': 'Edward Burns', 'gender': 2, 'depart...       Edward Burns
4800  [{'name': 'Carla Hetland', 'gender': 0, 'depar...        Scott Smith
4801  [{'name': 'Daniel Hsia', 'gender': 2, 'departm...        Daniel Hsia
4802  [{'name': 'Clark Peterson', 'gender': 2, 'depa...   Brian Herzlinger

                                   title_lower  \
0                                       avatar
1     pirates of the caribbean: at world's end
2                                      spectre
3                        the dark knight rises
4                                  john carter
...                                        ...
4798                               el mariachi
4799                                 newlyweds
4800                 signed, sealed, delivered
4801                          shanghai calling
4802                         my date with drew

                                   title_upper
0                                       AVATAR
1     PIRATES OF THE CARIBBEAN: AT WORLD'S END
2                                      SPECTRE
3                        THE DARK KNIGHT RISES
4                                  JOHN CARTER
...                                        ...
4798                               EL MARIACHI
4799                                 NEWLYWEDS
4800                 SIGNED, SEALED, DELIVERED
4801                          SHANGHAI CALLING
4802                         MY DATE WITH DREW

[4803 rows x 26 columns]

In [ ]:
from IPython.utils.text import strip_email_quotes
import pandas as pd
from scipy.spatial import distance

pointA = np.array([2,4,6])
pointB = np.array([5,1,9])

euclidean_distance = distance.euclidean(pointA,pointB)
print("euclidean_distance:", euclidean_distance)

similarity_distance = distance.cosine(pointA,pointB)
print("s_distance:", similarity_distance)

euclidean_distance: 5.196152422706632
s_distance: 0.12153793814103686

In [3]:
import numpy as np
import pandas as pd
from scipy.spatial import distance

pointA = np.array([2,4,6])
pointB = np.array([5,1,9])

# Euclidean Distance
euclidean_distance = distance.euclidean(pointA, pointB)
print("Euclidean Distance:", euclidean_distance)

# Similarity (inverse distance)
similarity = 1 / (1 + euclidean_distance)
print("Similarity:", similarity)

# Manhattan Distance
manhattan_distance = distance.cityblock(pointA, pointB)
print("Manhattan Distance:", manhattan_distance)

# Similarity (inverse distance)
similarity = 1 / (1 + manhattan_distance)
print("Similarity:", similarity)


#Minkowski Distance with p=3
minkowski_distance = distance.minkowski(pointA, pointB, p=2)
print("Minkowski Distance (p=3):", minkowski_distance)

#similarty(inverse of distance )
similarity_minkowski = 1 / (1 + minkowski_distance)
print("Similarity (p=2):", similarity_minkowski)

Euclidean Distance: 5.196152422706632
Similarity: 0.16139047779640892
Manhattan Distance: 9
Similarity: 0.1
Minkowski Distance (p=3): 5.196152422706632
Similarity (p=2): 0.16139047779640892

In [6]:
import pandas as pd
df = pd.DataFrame({
    'X': [10,20,30,40,50],
    'Y': [12,13,14,15,16]
})

corr_matrix  = df.corr()
print("PEarSON CORRELATION MATRIX:\n", corr_matrix)

PEarSON CORRELATION MATRIX:
      X    Y
X  1.0  1.0
Y  1.0  1.0

In [12]:
import pandas as pd
from scipy.stats import pearsonr

#load the dataset
tips = pd.read_csv('tips.csv')

corr,p_value = pearsonr(tips['total_bill'],tips['tip'])
print("correlation coefficient:",corr)
print("p-value:",p_value)

numeric_tips=tips.select_dtypes(include=['float64','int64'])

correlation coefficient: 0.6757341092113647
p-value: 6.692470646863279e-34

In [14]:
import pandas as pd
from scipy.stats import spearmanr

df = pd.DataFrame({
    'X': [10,20,30,40,50],
    'Y': [12,18,33,47,55]
})

corr_value, p_value = spearmanr(df['X'],df['Y'])
print("correlation coefficient:",corr_value)
print("p-value:",p_value)

correlation coefficient: 0.9999999999999999
p-value: 1.4042654220543672e-24

In [16]:
import pandas as pd
from scipy.stats import spearmanr
df = pd.read_csv('tips.csv')
corr_value, p_value = spearmanr(df['total_bill'],df['tip'])
print("spearman correlation coefficient:",corr_value)
print("p-value:",p_value)

spearman correlation coefficient: 0.6789681219001009
p-value: 2.501158440923619e-34

In [22]:
def hamming_distance(str1,str2):
  if len(str1) != len(str2):
    raise ValueError("Strings must have the same length")

  return sum(c1 != c2 for c1,c2 in zip(str1,str2))

s1 = 'pranathi'
s2= 'pranitha'

dist = hamming_distance(s1,s2)
print(f"hamming distance between '{s1}' and '{s2}': {dist}")

hamming distance between 'pranathi' and 'pranitha': 2

In [24]:
def jaccard_index(str1,str2):
  set1,set2 = set(str1.split()),set(str2.split())
  intersection = len(set1.intersection(set2))
  union = len(set1.union(set2))
  return intersection/union

s1 = "data science is fun"
s2 = "science makes data useful"

print("Jaccard index:", jaccard_index(s1,s2))

Jaccard index: 0.3333333333333333

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

s1 = "data science is fun"
s2 = "science makes data useful"

vectorizer = CountVectorizer().fit([s1,s2])
vectors = vectorizer.transform([s1,s2])

cos_sim= cosine_similarity(vectors[0],vectors[1])[0][0]
print("cosine similarity:",cos_sim)

cosine similarity: 0.5

In [31]:
def lcs_length(X,Y):
  m,n = len(X),len(Y)

  dp = [[0]*(n+1) for _ in range(m+1)]

  for i in range(m):
    for j in range(n):
      if X[i]==Y[j]:
        dp[i+1][j+1] = dp[i][j]+1
      else:
        dp[i+1][j+1] =max(dp[i][j+1],dp[i+1][j])
  return dp[m][n]

seq1 = "ABCDEF"
seq2 = "ABCDF"
length = lcs_length(seq1,seq2)
print(f"longest common subsequence length between '{seq1}' and '{seq2}': {length}")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3388375317.py, line 4)